language: node_js
node_js:
  - stable

install:
  - npm install

script:
  - npm run build

deploy:
  provider: s3
  access_key_id: YOUR_ACCESS_KEY
  secret_access_key: YOUR_SECRET_KEY
  bucket: YOUR_S3_BUCKET_NAME
  local_dir: build # Path to your built React app
  skip_cleanup: true
  on:
    branch: main # Or the branch you want to trigger deployment from
